### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by nickausten** [spark/particle-dev-profiles#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Ubuntu 18.10
**Thrown From**: [particle-dev-profiles](https://github.com/spark/particle-dev-profiles) package 0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /home/nicka/.atom/packages/particle-dev-profiles/src/profiles-tile.js:38

TypeError: Cannot read property 'name' of undefined
    at /packages/particle-dev-profiles/src/profiles-tile.js:38:96
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/scrollbar-style/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/scrollbar-style/node_modules/event-kit/lib/emitter.js:125:28)
    at ProfileManager.setLocal (/packages/particle-dev-profiles/src/profile-manager.js:123:16)
    at ProfileManager.set (/packages/particle-dev-profiles/src/profile-manager.js:252:8)
    at SelectCoreView.confirmed (/packages/particle-dev/lib/views/select-core-view.js:52:50)
    at SelectCoreView.module.exports.SelectListView.confirmSelection (/packages/console-panel/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /packages/console-panel/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/packages/console-panel/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/packages/console-panel/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:44.4.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always)
     -2:44.4.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always)
     -2:43.2.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:43.2.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:46.8.0 particle-dev:login (input.hidden-input)
     -1:08.9.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:08.9.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:08.8.0 particle-dev:update-login-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:08.8.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:08.8.0 particle-dev:update-login-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:55.7.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:55.7.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:55.6.0 particle-dev:select-device (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
console-panel 0.3.1 
git-plus 8.1.0 
git-time-machine 2.1.0 
overlay-status-icons 0.1.6 
particle-dev 0.2.2 
particle-dev-cloud-functions 0.2.0 
particle-dev-cloud-variables 0.2.0 
particle-dev-complete 1.0.2 
particle-dev-libraries 0.2.30 
particle-dev-local-compiler 0.1.3 
particle-dev-profiles 0.2.3 
tool-bar 1.1.11 
```

**Comment by nickausten** [comment]
Apologies - missed the "Steps to reproduce" - see #11 instead.
