### ISSUE TITLE
Failed to activate the particle-dev-profiles package

### ISSUE THREAD

**Issue by dhoerauf** [spark/particle-dev-profiles#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [particle-dev-profiles](https://github.com/spark/particle-dev-profiles) package, v0.1.9
### Stack Trace

Failed to activate the particle-dev-profiles package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at ProfilesTile.initialize (/home/darrell/.atom/packages/particle-dev-profiles/src/profiles-tile.js:23:22)
    at ProfilesTile.View [as constructor] (/home/darrell/.atom/packages/particle-dev-profiles/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ProfilesTile (/home/darrell/.atom/packages/particle-dev-profiles/src/profiles-tile.js:8:34)
    at Object.consumeStatusBar (/home/darrell/.atom/packages/particle-dev-profiles/src/main.js:27:10)
    at Provider.module.exports.Provider.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/opt/atom/resources/app.asar/src/package.js:363:75)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:186:16)
    at /opt/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:538:21)
    at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:397:31
```
### Commands

```
     -1:51.8.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:51.8.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:51.8.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:51.8.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:55.7.0 settings-view:uninstall-packages (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
console-panel, v0.2.0 (active)
docker, v0.7.0 (inactive)
language-particle, v0.3.4 (active)
particle-dev, v0.1.5 (active)
particle-dev-cloud-functions, v0.1.0 (active)
particle-dev-cloud-variables, v0.1.0 (active)
particle-dev-complete, v1.0.0 (active)
particle-dev-local-compiler, v0.0.4 (active)
particle-dev-profiles, v0.1.9 (inactive)
particle-dev-release-notes, v0.53.2 (active)
particle-offline-compiler, v0.1.3 (active)
tool-bar, v1.0.1 (active)
tool-bar-main, v0.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by suda** [comment]
@dhoerauf I can't reproduce this error. Additionally, this should have been fixed in 0.1.7. Could you try running `apm rebuild-module-cache` or removing `~/.atom/compile-cache` directory?

**Comment by EdwinLocker** [comment]
I have the exact same problem when I first opened the Particle Dev.
What can I do ?

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Win 10 pro
**Thrown From**: [particle-dev-profiles](https://github.com/spark/particle-dev-profiles) package, v0.1.15


### Stack Trace

Failed to activate the particle-dev-profiles package

```
At rticle is not defined

ReferenceError: rticle is not defined
    at Object.<anonymous> (C:/ProgramData/Lucas/particledev/app-1.8.0/resources/app.asar/node_modules/particle-dev-profiles/src/main.js:33:2)
    at Module._compile (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:/Users/Lucas/AppData/Local/particledev/app-1.8.0/resources/app.asar/node_modules/particle-dev/node_modules/atom-package-deps/lib/main.js:21:23
    at Array.forEach (native)
    at Object.install (C:/Users/Lucas/AppData/Local/particledev/app-1.8.0/resources/app.asar/node_modules/particle-dev/node_modules/atom-package-deps/lib/main.js:14:15)
    at Object.module.exports.activate (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\node_modules\particle-dev\lib\main.js:78:36)
    at Package.module.exports.Package.activateNow (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\Lucas\AppData\Local\particledev\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```

### Commands

```
     -0:03.7.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always)
     -0:03.7.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always)
     -0:03.6.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always)
     -0:02.5.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:02.5.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:02.5.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:02.5.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-clock, v0.1.8

# Dev
No dev packages
```
