### ISSUE TITLE
Failed to activate the particle-dev-profiles package

### ISSUE THREAD

**Issue by jonatanrosman** [spark/particle-dev-profiles#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [particle-dev-profiles](https://github.com/spark/particle-dev-profiles) package 0.2.3

### Stack Trace

Failed to activate the particle-dev-profiles package

```
At Cannot find module 'particle-api-js'

Error: Cannot find module 'particle-api-js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:12240:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11585:33)
    at /packages/particle-dev-profiles/src/profile-manager.js:11:22)
    at /packages/particle-dev-profiles/src/profile-manager.js:478:3)
    at Module.get_Module._compile (<embedded>:11625:36)
    at Object.value [as .js] (<embedded>:11876:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11585:33)
    at Object.activate (/packages/particle-dev-profiles/src/main.js:17:20)
    at Package.module.exports.Package.activateNow (<embedded>:72535:25)
    at <embedded>:72507:38
    at Package.module.exports.Package.measure (<embedded>:72379:21)
    at <embedded>:72500:32
    at Package.module.exports.Package.activate (<embedded>:72497:40)
    at PackageManager.activatePackage (<embedded>:25356:42)
    at config.transactAsync (<embedded>:25331:36)
    at Config.module.exports.Config.transactAsync (<embedded>:22003:24)
    at PackageManager.activatePackages (<embedded>:25329:23)
    at PackageManager.activate (<embedded>:25308:50)
    at <embedded>:1103:36

```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.9 
atom-live-server 2.2.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.15 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-pigments 0.2.2 
particle-dev 0.2.2 
particle-dev-cloud-functions 0.2.0 
particle-dev-cloud-variables 0.2.0 
particle-dev-complete 1.0.2 
particle-dev-libraries 0.2.30 
particle-dev-profiles 0.2.3 
pigments 0.40.2 
todo 0.6.0 
```

**Comment by suda** [comment]
Hi Jonatan! This might be caused by the package not getting installed correctly. Could you try reinstalling the package again? You can also try running `apm rebuild-module-cache` in your terminal.
